# Generated by Django 3.0.4 on 2020-06-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personaapp', '0002_auto_20200604_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='personaapp.Habilidades'),
        ),
    ]
