# Generated by Django 3.0.4 on 2020-06-04 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentoapp', '0002_auto_20200602_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['name'], 'verbose_name': 'Mi Departamento', 'verbose_name_plural': 'Areas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
